spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    path: /error
    whitelabel:
      enabled: false
  port: 8080

